/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.interview.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Interview service. Represents a row in the &quot;Interview_Interview&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.interview.model.impl.InterviewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.interview.model.impl.InterviewImpl}.
 * </p>
 *
 * @author Sara Liu
 * @see Interview
 * @see com.liferay.interview.model.impl.InterviewImpl
 * @see com.liferay.interview.model.impl.InterviewModelImpl
 * @generated
 */
public interface InterviewModel extends BaseModel<Interview> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a interview model instance should use the {@link Interview} interface instead.
	 */

	/**
	 * Returns the primary key of this interview.
	 *
	 * @return the primary key of this interview
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this interview.
	 *
	 * @param primaryKey the primary key of this interview
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this interview.
	 *
	 * @return the uuid of this interview
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this interview.
	 *
	 * @param uuid the uuid of this interview
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the interview ID of this interview.
	 *
	 * @return the interview ID of this interview
	 */
	public long getInterviewId();

	/**
	 * Sets the interview ID of this interview.
	 *
	 * @param interviewId the interview ID of this interview
	 */
	public void setInterviewId(long interviewId);

	/**
	 * Returns the user ID of this interview.
	 *
	 * @return the user ID of this interview
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this interview.
	 *
	 * @param userId the user ID of this interview
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this interview.
	 *
	 * @return the user uuid of this interview
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this interview.
	 *
	 * @param userUuid the user uuid of this interview
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this interview.
	 *
	 * @return the create date of this interview
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this interview.
	 *
	 * @param createDate the create date of this interview
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this interview.
	 *
	 * @return the modified date of this interview
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this interview.
	 *
	 * @param modifiedDate the modified date of this interview
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this interview.
	 *
	 * @return the name of this interview
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this interview.
	 *
	 * @param name the name of this interview
	 */
	public void setName(String name);

	/**
	 * Returns the email address of this interview.
	 *
	 * @return the email address of this interview
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this interview.
	 *
	 * @param emailAddress the email address of this interview
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the start date of this interview.
	 *
	 * @return the start date of this interview
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this interview.
	 *
	 * @param startDate the start date of this interview
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the expire date of this interview.
	 *
	 * @return the expire date of this interview
	 */
	public Date getExpireDate();

	/**
	 * Sets the expire date of this interview.
	 *
	 * @param expireDate the expire date of this interview
	 */
	public void setExpireDate(Date expireDate);

	/**
	 * Returns the question set ID of this interview.
	 *
	 * @return the question set ID of this interview
	 */
	public long getQuestionSetId();

	/**
	 * Sets the question set ID of this interview.
	 *
	 * @param questionSetId the question set ID of this interview
	 */
	public void setQuestionSetId(long questionSetId);

	/**
	 * Returns the response of this interview.
	 *
	 * @return the response of this interview
	 */
	@AutoEscape
	public String getResponse();

	/**
	 * Sets the response of this interview.
	 *
	 * @param response the response of this interview
	 */
	public void setResponse(String response);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Interview interview);

	public int hashCode();

	public CacheModel<Interview> toCacheModel();

	public Interview toEscapedModel();

	public String toString();

	public String toXmlString();
}