/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.interview.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.interview.model.QuestionSet;
import com.liferay.interview.service.InterviewLocalService;
import com.liferay.interview.service.QuestionLocalService;
import com.liferay.interview.service.QuestionSetLocalService;
import com.liferay.interview.service.persistence.InterviewPersistence;
import com.liferay.interview.service.persistence.QuestionPersistence;
import com.liferay.interview.service.persistence.QuestionSetPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the question set local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.interview.service.impl.QuestionSetLocalServiceImpl}.
 * </p>
 *
 * @author Sara Liu
 * @see com.liferay.interview.service.impl.QuestionSetLocalServiceImpl
 * @see com.liferay.interview.service.QuestionSetLocalServiceUtil
 * @generated
 */
public abstract class QuestionSetLocalServiceBaseImpl
	implements QuestionSetLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.interview.service.QuestionSetLocalServiceUtil} to access the question set local service.
	 */

	/**
	 * Adds the question set to the database. Also notifies the appropriate model listeners.
	 *
	 * @param questionSet the question set
	 * @return the question set that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public QuestionSet addQuestionSet(QuestionSet questionSet)
		throws SystemException {
		questionSet.setNew(true);

		return questionSetPersistence.update(questionSet, false);
	}

	/**
	 * Creates a new question set with the primary key. Does not add the question set to the database.
	 *
	 * @param questionSetId the primary key for the new question set
	 * @return the new question set
	 */
	public QuestionSet createQuestionSet(long questionSetId) {
		return questionSetPersistence.create(questionSetId);
	}

	/**
	 * Deletes the question set with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param questionSetId the primary key of the question set
	 * @return the question set that was removed
	 * @throws PortalException if a question set with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public QuestionSet deleteQuestionSet(long questionSetId)
		throws PortalException, SystemException {
		return questionSetPersistence.remove(questionSetId);
	}

	/**
	 * Deletes the question set from the database. Also notifies the appropriate model listeners.
	 *
	 * @param questionSet the question set
	 * @return the question set that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public QuestionSet deleteQuestionSet(QuestionSet questionSet)
		throws SystemException {
		return questionSetPersistence.remove(questionSet);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return questionSetPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return questionSetPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return questionSetPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return questionSetPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public QuestionSet fetchQuestionSet(long questionSetId)
		throws SystemException {
		return questionSetPersistence.fetchByPrimaryKey(questionSetId);
	}

	/**
	 * Returns the question set with the primary key.
	 *
	 * @param questionSetId the primary key of the question set
	 * @return the question set
	 * @throws PortalException if a question set with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public QuestionSet getQuestionSet(long questionSetId)
		throws PortalException, SystemException {
		return questionSetPersistence.findByPrimaryKey(questionSetId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return questionSetPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the question sets.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of question sets
	 * @param end the upper bound of the range of question sets (not inclusive)
	 * @return the range of question sets
	 * @throws SystemException if a system exception occurred
	 */
	public List<QuestionSet> getQuestionSets(int start, int end)
		throws SystemException {
		return questionSetPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of question sets.
	 *
	 * @return the number of question sets
	 * @throws SystemException if a system exception occurred
	 */
	public int getQuestionSetsCount() throws SystemException {
		return questionSetPersistence.countAll();
	}

	/**
	 * Updates the question set in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param questionSet the question set
	 * @return the question set that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public QuestionSet updateQuestionSet(QuestionSet questionSet)
		throws SystemException {
		return updateQuestionSet(questionSet, true);
	}

	/**
	 * Updates the question set in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param questionSet the question set
	 * @param merge whether to merge the question set with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the question set that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public QuestionSet updateQuestionSet(QuestionSet questionSet, boolean merge)
		throws SystemException {
		questionSet.setNew(false);

		return questionSetPersistence.update(questionSet, merge);
	}

	/**
	 * Returns the interview local service.
	 *
	 * @return the interview local service
	 */
	public InterviewLocalService getInterviewLocalService() {
		return interviewLocalService;
	}

	/**
	 * Sets the interview local service.
	 *
	 * @param interviewLocalService the interview local service
	 */
	public void setInterviewLocalService(
		InterviewLocalService interviewLocalService) {
		this.interviewLocalService = interviewLocalService;
	}

	/**
	 * Returns the interview persistence.
	 *
	 * @return the interview persistence
	 */
	public InterviewPersistence getInterviewPersistence() {
		return interviewPersistence;
	}

	/**
	 * Sets the interview persistence.
	 *
	 * @param interviewPersistence the interview persistence
	 */
	public void setInterviewPersistence(
		InterviewPersistence interviewPersistence) {
		this.interviewPersistence = interviewPersistence;
	}

	/**
	 * Returns the question local service.
	 *
	 * @return the question local service
	 */
	public QuestionLocalService getQuestionLocalService() {
		return questionLocalService;
	}

	/**
	 * Sets the question local service.
	 *
	 * @param questionLocalService the question local service
	 */
	public void setQuestionLocalService(
		QuestionLocalService questionLocalService) {
		this.questionLocalService = questionLocalService;
	}

	/**
	 * Returns the question persistence.
	 *
	 * @return the question persistence
	 */
	public QuestionPersistence getQuestionPersistence() {
		return questionPersistence;
	}

	/**
	 * Sets the question persistence.
	 *
	 * @param questionPersistence the question persistence
	 */
	public void setQuestionPersistence(QuestionPersistence questionPersistence) {
		this.questionPersistence = questionPersistence;
	}

	/**
	 * Returns the question set local service.
	 *
	 * @return the question set local service
	 */
	public QuestionSetLocalService getQuestionSetLocalService() {
		return questionSetLocalService;
	}

	/**
	 * Sets the question set local service.
	 *
	 * @param questionSetLocalService the question set local service
	 */
	public void setQuestionSetLocalService(
		QuestionSetLocalService questionSetLocalService) {
		this.questionSetLocalService = questionSetLocalService;
	}

	/**
	 * Returns the question set persistence.
	 *
	 * @return the question set persistence
	 */
	public QuestionSetPersistence getQuestionSetPersistence() {
		return questionSetPersistence;
	}

	/**
	 * Sets the question set persistence.
	 *
	 * @param questionSetPersistence the question set persistence
	 */
	public void setQuestionSetPersistence(
		QuestionSetPersistence questionSetPersistence) {
		this.questionSetPersistence = questionSetPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.liferay.interview.model.QuestionSet",
			questionSetLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.liferay.interview.model.QuestionSet");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected ClassLoader getClassLoader() {
		Class<?> clazz = getClass();

		return clazz.getClassLoader();
	}

	protected Class<?> getModelClass() {
		return QuestionSet.class;
	}

	protected String getModelClassName() {
		return QuestionSet.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = questionSetPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = InterviewLocalService.class)
	protected InterviewLocalService interviewLocalService;
	@BeanReference(type = InterviewPersistence.class)
	protected InterviewPersistence interviewPersistence;
	@BeanReference(type = QuestionLocalService.class)
	protected QuestionLocalService questionLocalService;
	@BeanReference(type = QuestionPersistence.class)
	protected QuestionPersistence questionPersistence;
	@BeanReference(type = QuestionSetLocalService.class)
	protected QuestionSetLocalService questionSetLocalService;
	@BeanReference(type = QuestionSetPersistence.class)
	protected QuestionSetPersistence questionSetPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
}